name: whatsapp_clone_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  contacts_service: ^0.6.3
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.1.2
  video_player: ^2.9.2
  file_picker: ^8.3.5

  firebase_storage: ^12.4.2
  country_pickers: ^3.0.1
  flutter_pin_code_fields: ^2.2.0
  cached_network_image: ^3.4.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  font_awesome_flutter: ^10.8.0
  agora_uikit: ^1.3.10
  swipe_to: ^1.0.6
  emoji_picker_flutter: ^4.3.0
  intl: ^0.19.0
  get_time_ago: ^2.2.0

  giphy_picker: ^3.0.2
  path_provider: ^2.1.5
  audioplayers: ^6.1.2
  just_audio: ^0.9.46
  flutter_story_view: ^0.0.4
  flutter_sound: ^9.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_image.png
    - assets/meta.png
    - assets/profile_default.png
    - assets/whats_app_logo.png
    - assets/whatsapp_bg_image.png
