name: whatsapp_clone_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.11
  intl: ^0.20.2
  country_pickers: ^3.0.1
  flutter_pin_code_fields: ^2.2.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_image.png
    - assets/meta.png
    - assets/profile_default.png
    - assets/whats_app_logo.png
    - assets/whatsapp_bg_image.png
